
import { runError } from 'client/helpers/run-error';
import { module, test } from 'qunit';

module('Unit | Helper | run error');

// Replace this with your real tests.
test('it works', function(assert) {
  let result = runError([42]);
  assert.ok(result);
});

